# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            My Projects Devlog
tagline:          'Enter my train of thought!'
description:      'Where I explain, reason, and solve problems'
url:              http://denniswd.me

author:
  name:           'Dennis Walangadi'
  url:            https://twitter.com/dawalangadi

paginate:         5

# Custom vars
version:          1

github:
  repo:           https://github.com/arken4/arken4.github.io
